### ISSUE TITLE
Deprecated error with php8

### ISSUE THREAD

**Issue by yndu13** [adbario/php-dot-notation#33]
Error Message:
PHP Deprecated:  Return type of Adbar\Dot::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/dyn/AliGitRepo/openapi-sdk-php-client/vendor/adbario/php-dot-notation/src/Dot.php on line 603

"adbario/php-dot-notation": "^2.3"

**Comment by nicojmb** [comment]
Same problema here, added "@" temporarily

**Comment by adbario** [comment]
@yndu13 @nicojmb

If you're on v2.3, it supports PHP up to 8.1.

For some reason, the release seems to be dated in 2019 though, so I'm assuming something has gone wrong. I've just done a new release as v2.4, and that should fix the issue. All the [automated tests are passing](https://github.com/adbario/php-dot-notation/runs/7869158186?check_suite_focus=true) on PHP 5.5 -> PHP 8.1 

Let me know if 2.4 doesn't fix the issues.

There's also a v3 which adds some additional features but supports only PHP 7.4 and up.

**Comment by jamisonbryant** [comment]
@adbario Not sure what changed between 2.2 and 2.4, but the issue remains. We either need the return type changed to `mixed` or the same annotation added to jsonSerialize as was added to getIterator (`#[\ReturnTypeWillChange]`).

This is causing deprecation warnings to pop up in downstream libraries, could we possibly get this fixed real quick?

**Comment by adbario** [comment]
Thanks @jamisonbryant, your PR was just approved and a new release is out. I'm surprised that you've seen deprecation warnings as all the tests were passing already before, but hopefully this fixes the issue now.

**Comment by jamisonbryant** [comment]
You're welcome, glad to be of service! Thank you for responding so quickly.
